version: '3.8'
services:
  teslo-shop-db:
    image: postgres:16.2-bullseye
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - teslo-shop-data:/var/lib/postgresql/data

volumes:
  teslo-shop-data:
