version: '3.8'
services:
  pokedex-db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - pokedex-db:/data/db
    env_file:
      - .env.prod

  pokedex-api:
    build:
      context: .
      dockerfile: ./dockerfiles/nestjs/Dockerfile
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env.prod
    depends_on:
      - pokedex-db

volumes:
  pokedex-db:
