version: '3.8'
services:
  pokedex-db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - pokedex-db:/data/db
    env_file:
      - .env

volumes:
  pokedex-db:
